# Generated by Django 5.1.2 on 2024-11-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_remove_trainer_certification_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'managed': False},
        ),
    ]
