# Generated by Django 5.1.2 on 2024-11-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainer_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainer',
            table='trainer',
        ),
    ]
