# Generated by Django 5.1.2 on 2024-10-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('pilot_id', models.AutoField(primary_key=True, serialize=False)),
                ('pilot_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pilot',
                'managed': False,
            },
        ),
    ]
