# Generated by Django 5.1.2 on 2024-10-31 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilots', '0001_initial'),
        ('trainers', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.pilot')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingprogram')),
            ],
        ),
    ]
