# Generated by Django 5.1.2 on 2024-11-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'managed': False},
        ),
    ]
