# Generated by Django 5.1.2 on 2024-11-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_trainingprogram_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainingprogram',
            table='trainingprogram',
        ),
    ]
